### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by Raymo111**

### CODE REVIEW

**Comment by Raymo111** [comment]
Err @reteps what exactly did you change in cb86f1c9d1e99d3c93c63f5eb0b0d46807c92d3b?

**Comment by reteps** [comment]
lol i had a very descriptive message

**Comment by reteps** [comment]
not sure, i think i fixed it to work with a new kahoot update

**Comment by reteps** [comment]
also - i switched to windows which changed all the line endings

**Comment by Raymo111** [comment]
> not sure, i think i fixed it to work with a new kahoot update

You're not sure about code you wrote? Do our repos both work now?

**Pull request closed without merging**
